### PR TITLE
[WIP] Assetchain conf

### PR DESCRIPTION
**Pull request by lukechilds**
Following on from the [discussion in Discord](https://discordapp.com/channels/412898016371015680/455755767132454913/461402924262883328) I've put together an example of what an asset chain configuration file might look like.

The idea being that the main repo doesn't hardcode all the parameters into a specific init script, but instead exposes the required data.

This would allow notary nodes (or anyone else who wants to run AC nodes) to develop their own init scripts and tool chains that use the provided data. Currently people have to hardcode asset chain params into their own code and try and keep them in sync with the Komodo repo.

I've provided an example `assetchains.json` file and updated the current init script to use that instead.

**This is a work in progress and is not ready to be merged yet. Just opening this PR for discussion.**

### CODE REVIEW

**Comment by emmnx** [comment]
This `+    "params": "-ac_name=REVS -ac_supply=1300000"` is not correct, please make it

```
"params": ["ac_name": "REVS", "ac_supply": "1300000"]
```

**Comment by blackjok3rtt** [comment]
Why like that.... that makes it even harder. We had a fairly long discussion about that. There is no reason at all to split them like that, the AC params are AC params, everything else is optional.

**Comment by emmnx** [comment]
There is a reason for that. You need to keep data structure consistent. Two keys and their two values aren't a string. They are two keys, and two values.

**Comment by blackjok3rtt** [comment]
But they are the same value, the "params" value is not optional, changing any one of those values will change the chains rpcport and magic value, so they are one thing. Why over complicate things?

**Comment by emmnx** [comment]
What is so complicated about it? I don't understand. 
Data is data, it doesn't need to know what is mandatory and what not. Software needs to know that, not data.

**Comment by kolobus** [comment]
@blackjok3rtt Think of params as not a static thing from file. It can be generated elswhere to get needed list of assets to run. Not just string in file.

Adding optional gen param will be double awesome.

**Comment by emmnx** [comment]
@patchkez made me realize that this registry already exists:
https://github.com/emmnx/iguana-tools/blob/master/initialization/coins_json.py
The only missing value is "supply".

**Comment by patchkez** [comment]
@emmnx I think coins_json.py is not valid JSON, but I get your point. 

I see this PR as different problems:
1. Central registry file - this is actually content of coins/ folder in Supernet repository. Each file contains JSON payload + curl command. We should rename each file to <coin>.json, remove curl command from there, and execute call with `curl -d @coins/<coin> http://iguana`.
This will have advantage that json files can be now formatted nicely, without backslashes and users can parse json payload in their favourite language.
It would be even better to have just one central file, instead of file per coin.
@jl777 'supply' which is needed for starting assetchains is not in this file, would it be problem to add it into each coins/*_7776 file? Question is if iguana won't complain that there are some other keys in the JSON payload. 

2. Once we have central registry in place we might need central config file for Notary Node. This config would tell you which assetchains to start, which assetchains to notarize, what IPs to use during addnode iguana call, ... There will be functions which parses config file and executes what is needed e.g. curl against iguana

With this written above, I am not sure how we could access coins/ folder in jl777/Supernet from jl777/komodo repository. 
I noticed that coins/vrsc_7776 file does not contain all params needed for starting daemon (e.g. ac_reward, ac_halving, ..).

I vote to not have strings in JSON and use just keys, values. If we have troubles parsing it with jq, we can add external parser for it. It can be python script, go binary or compiled C program, .... Parser will just read JSON file and prints it out in desired format which can be parsed in bash. We could even use INI file for Central configuration file (described in 2.) which can be parsed by external parser. 

@lukechilds I noticed that rpcPort/s in your JSON are already defined in coins/* Supernet repo. If we would follow points 1./2. we would not need your JSON, just central config file which tells us what assetchains to start and corresponding function which would loop through central registry/data file (for corresponding coins defined in config) and start komodod with desired parameters.

**Comment by lukechilds** [comment]
@emmnx 

>This `+ "params": "-ac_name=REVS -ac_supply=1300000"` is not correct, please make it
>
>```
>"params": ["ac_name": "REVS", "ac_supply": "1300000"]
>```

That's invalid JSON. Only objects can have key:value pairs which would look like this:

```js
{
	"params": {
		"ac_name": "REVS",
		"ac_supply": "1300000"
	}
}
```

However objects don't allow duplicate properties which means it's not possible to express duplicate CLI arguments.

To allow for duplicate arguments you would have to express it as an array of arrays like this:

```js
{
	"params": [
		["ac_name", "REVS"],
		["ac_supply", "1300000"]
	]
}
```

That makes parsing a bit more complicated, the `jq` would now be:

```shell
jq '.[].params | map("-\(.[0])=\(.[1])") | reduce .[1:][] as $i ("\(.[0])"; . + " \($i)")
```

I don't have a problem with this if people want to query CLI args. But does anyone actually need to do that?

There are more cons to this method IMO, it's harder to parse and more error prone to update, however if people need this format I don't have an issue with it.

@kolo

>Adding optional gen param will be double awesome.

I don't think that belongs in the JSON, that's more of a user option than a specific chain parameter. I updated the init script (https://github.com/jl777/komodo/pull/705/commits/fc6aca1ff9263ff31101930cf74b02ce24cfbed1) to use the JSON and didn't change any of the existing logic, so it still adds `-gen` to 10% of chains randomly. But I imagine this is probably something most NNs would want to manage in their own scripts.

@patchkez 

>I noticed that rpcPort/s in your JSON are already defined in coins/* Supernet repo. If we would follow points 1./2. we would not need your JSON, just central config file which tells us what assetchains to start and corresponding function which would loop through central registry/data file (for corresponding coins defined in config) and start komodod with desired parameters.

If we don't need JSON that's fine by me. I'm only using JSON as people wanted to be able to query other data such as ports for configuring Docker images. I would prefer just a text file like:

```
$ cat assetchainparams.txt
-ac_name=ZILLA -ac_supply=11000000 -addnode=54.39.23.248
-ac_name=RFOX -ac_supply=1000000000 -ac_reward=100000000
```

That's fool proof to update and people can just loop over the output and run `komodod` with the args plus any extra args they want to add such as `-gen`.

**Comment by lukechilds** [comment]
@emmnx There's nothing complicated with parsing that, the problem with using a key:value object is that it doesn't support duplicate keys. For example the args:

`-ac_name=FOO -ac_supply=100 -foo=bar -foo=fizz`

Are impossible to express in that format. You could write them like this:

```js
{
	"params": {
		"ac_name": "FOO",
		"ac_supply": "100",
		"foo": "bar",
		"foo": "fizz"
	}
}
```

However that's invalid JSON. You will either get a parse error, or end up with only one `foo` property.

Also, in your example you are hardcoding the arguments in the file assuming they are the only ones that exist. It would fail if someone added a new AC that used a new CLI arg. To correctly handle that you would need to loop over the object properties, as opposed to directly access a list of hardcoded properties.

To allow for duplicate arguments we need to use an array of arrays, which looks like this:

```js
{
	"params": [
		["ac_name", "FOO"],
		["ac_supply", "100"],
		["foo", "bar"],
		["foo", "fizz"]
	]
}
```

And could be parsed in python like this:

```python
import json

with open('assetchains.json') as file:
    assetchains = json.load(file)

for chain in assetchains:
    params = chain['params']
    params = map((lambda param: '-' + param[0] + '=' + param[1]), params)
    params = ' '.join(params)
    print(params)

# -ac_name=FOO -ac_supply=100 -foo=bar -foo=fizz
# -ac_name=BAR -ac_supply=100 -foo=bar -foo=fizz
```

**Comment by lukechilds** [comment]
Yeah we discussed that exact structure in Discord, but the array structure seemed to be preferred. I don't really have a problem with either.

Using an object it's no longer a simple transform on a structure, you now have to check a value to see if it's an array or a string and handle it differently.

It's also more ambiguous. If you don't understand how it's supposed to be parsed you could easily confuse:

```js
{
	"foo": [
		"bar",
		"bazz"
	]
}
```

as meaning:

```
-foo=bar,bazz
```

as opposed to:

```
--foo=bar -foo=bazz
```

With an array of arrays it's pretty unambiguous:

```js
[
	["foo", "bar"],
	["foo", "bazz"]
]
```

But I'm pretty happy with either. And I guess being able to directly query for properties is nicer than having to filter them out of the array.

One other thing to be aware of is that in JSON, arrays are ordered while object properties are not. That means if you store the params as object properties you aren't guaranteed to loop over them in the same order. I'm not sure if order is important for AC args, I don't think they are, but worth baring in mind.

**Comment by emmnx** [comment]
Yes, that's the point that I was trying to make, if it's an ordered list or not. 
In this case it's clearly just keys and value.

The main problem here is that we're trying to adapt 3D data to a 2D model (command line, what we're used to see). And we shouldn't. Because under the hood, it's all 3D data, not just -parameter=value.

The solution, imo, is improving the code that manages that 3D data (and no workarounds).

**Comment by lukechilds** [comment]
Ok, that makes sense to me, as long as someone can confirm that the order of the arguments definitely doesn't matter, I know the params are used to generate a custom port number (@jl777?).

But if they don't then you've sold me on properties, with either a string value or an array of strings.

Regarding port numbers and other metadata, did we decide that doesn't belong here now? Should `assetchains.json` just be purely a list of assetchain arg objects?

So we can drop the need for a `params` property shave this down to just a list of param arrays:

```js
[
  {
    "ac_name": "FOO",
    "ac_supply": "100",
    "foo": [
      "bar",
      "fizz"
    ]
	},
  {
    "ac_name": "BAR",
    "ac_supply": "100",
    "foo": [
      "bar",
      "fizz"
    ]
  }
]
```

**Comment by emmnx** [comment]
I'm not sure about the shape that a unified single registry should have.
Having separate .json files, one for addcoin method calls (like [this](https://github.com/emmnx/iguana-tools/blob/master/initialization/coins.json) that I'm already using) and other (this new one) for starting daemons, can be a valid option, because they are actually two different stages handled by two different tools (iguana and komodod).

**Comment by jl777** [comment]
order of parameters doesnt matter

**Comment by patchkez** [comment]
@emmnx @lukechilds Not sure if it is good idea, but maybe we can include also JSON for importing private key into assetchains:
```
{
    "agent": "bitcoinrpc",
    "method": "importprivkey",
    "params": [$PRIVKEY, "", $RESCAN]
}
```
But for this to work, we would need to know rpc port number of assetchains daemons which we do not have (in this repo). 
Maybe it is all what we need for now - asset params + dpow.
Have we decided how we will parse JSON data? @lukechilds you want to use `jq` for that?

**Comment by emmnx** [comment]
@lukechilds do assetchains have particular values for the dpow method? 
I'm starting all of them with this function:
https://github.com/emmnx/iguana-tools/blob/master/initialization/init_iguana.py#L304
Pubkey is already being included there too, as you can see.

The only thing that I need to feed to my iguana with is [the addcoin method data.](https://github.com/emmnx/iguana-tools/blob/master/initialization/coins.json)

At first I thought that unifying both files (this new file that we're discussing here, to start assetchains, and this other addcoin calls file of mine) was a good idea.

But then I realized that iguana names things differently than komodod. So probably the best option is keeping them separated. Maybe store them in the same database in the future, but in separated tables, as they represent two very different stages managed by two different tools.

**Comment by patchkez** [comment]
@emmnx It seems dpow methods for some coins have `freq` key defined with different values:
https://github.com/jl777/komodo/blob/dev/src/dpowassets

**Comment by emmnx** [comment]
@patchkez 
_init_iguana.py_ already manages private keys dynamically. 
https://github.com/emmnx/iguana-tools/blob/master/initialization/init_iguana.py#L281
This script is made for anyone running iguana, not only containers users.

**Comment by emmnx** [comment]
@patchkez interesting. 

In that case we should think of a third file, or merging this to my unified addcoin method file, as they both correspond to iguana.

Maybe @jl777 it makes sense taking this "freq" parameter from dpow method to addcoin method? I don't even know if that makes sense from iguana's code point of view, just asking.

In case it stays on the dpow method, we can just merge both sets of data by letting that parameter "freq" on the same file as addcoin method calls, and using it separately at code level (I can modify init_iguana.py to take it into consideration).

**Comment by lukechilds** [comment]
@patchkez 

>Not sure if it is good idea, but maybe we can include also JSON for importing private key into assetchains:

We shouldn't include anything to do with the priv key here, that's user specific and should be handled dynamically by the run script.

>Have we decided how we will parse JSON data? @lukechilds you want to use `jq` for that?

Yeah, we will use Python. It's getting a bit too complex for `jq` and Python is more likely to be pre-installed.

@emmnx 

>do assetchains have particular values for the dpow method?

You can see the iguana commands here:
https://github.com/jl777/SuperNET/blob/dev/iguana/m_notary_run
https://github.com/jl777/SuperNET/blob/dev/iguana/coins/kmd_7776
https://github.com/jl777/komodo/blob/dev/src/dpowassets

I wasn't actually aware of all these commands as I've been using the built in run scripts in the repos for iguana. I had no idea there were so many calls split between the repos and different files.

>At first I thought that unifying both files (this new file that we're discussing here, to start assetchains, and this other addcoin calls file of mine) was a good idea.
>
>But then I realized that iguana names things differently than komodod. So probably the best option is keeping them separated.

Yeah, I definitely agree. Also, the `assetchains.json` is just for asset chain params. It could be useful to non notary nodes who just want to run asset chain nodes. The iguana commands are specific to notary nodes and also contain commands for full nodes that aren't asset chains, such as BTC,KMD,GAME,VRSC etc.

I would propose we have an `assetchains.json` like discussed here. Then a separate `notarycommands.json` which contains iguana JSON paramters for all coins and assetchains. You would still need to manually add your pubkey to these commands, but it would all be scriptable and automated.

I also think we should focus on getting `assetchains.json` finalised and implemented for now. Once that's merged, I can add the iguana commands in a follow up PR.

So for `assetchains.json`, is everyone happy with the format:

```js
[
  {
    "ac_name": "FOO",
    "ac_supply": "100",
    "foo": "bar"
	},
  {
    "ac_name": "BAR",
    "ac_supply": "100",
    "foo": [
      "bar",
      "fizz"
    ]
  }
]
```

**Comment by emmnx** [comment]
I think that it is safe to merge all addcoin and dpow method parameters in my coins.json file, and the code will pick what it needs at each function. I'll do that tomorrow.

**Comment by lukechilds** [comment]
Ok, I've updated the JSON to match the agreed format. Also updated with latest assetchain params from dev branch.

I've scrapped `jq` there is now a python script at `src/assetchainparams` that will parse the JSON into a list of args for people who don't want to write their own JSON parsing logic but would still like to build a simple custom script looping over a list of params.

I've also refactored the default `src/assetchains` script to use the `src/assetchainparams` script internally which in turn parses the JSON.

So future updates should be made **only** to the JSON file. Then peoples custom scripts, the `src/assetchainparams` script, and the default  `src/assetchains` script will all inherit the new values.

Example:

```shell
$ ./assetchainparams
-ac_supply=1300000 -ac_name=REVS
-ac_supply=816061 -ac_name=SUPERNET
-ac_supply=999999 -ac_name=DEX
-ac_supply=999999 -ac_name=PANGEA
-ac_supply=999999 -ac_name=JUMBLR
-ac_supply=999999 -ac_name=BET
-ac_supply=999999 -ac_name=CRYPTO
-ac_supply=9999999 -ac_name=HODL
-ac_supply=1400000 -ac_name=MSHARK
-ac_supply=999999 -ac_name=BOTS
-ac_supply=999999 -ac_name=MGW
-ac_supply=72000000 -ac_name=COQUI
-ac_supply=210000000 -ac_name=WLC
-ac_supply=1000000 -ac_name=KV
-ac_supply=366666666 -ac_name=CEAL
-ac_supply=1000007 -ac_name=MESH
-ac_supply=257142858 -ac_name=MNZ
-ac_supply=200000000 -ac_name=AXO
-ac_supply=100000000 -ac_name=ETOMIC
-ac_supply=20998641 -ac_name=BTCH
-ac_supply=100000000 -ac_name=PIZZA
-ac_supply=100000000 -ac_name=BEER
-ac_supply=100000000 -ac_name=NINJA
-ac_supply=216000000 -ac_name=OOT
-ac_supply=500000000 -ac_name=BNTN
-ac_supply=999999 -ac_name=CHAIN
-ac_supply=500000000 -ac_name=PRLPAY
-ac_supply=7000000 -ac_name=DSEC
-ac_supply=10000000000 -ac_name=GLXT
-ac_supply=500000000 -ac_name=EQL
-ac_supply=11000000 -ac_name=ZILLA
-ac_supply=1000000000 -ac_name=RFOX -ac_reward=100000000
```

Although not a current requirement, if any assetchains in the future require duplicate parameters, the script will handle that.

Example:

```js
[
	...
  {
    "ac_name": "RFOX",
    "ac_supply": "1000000000",
    "ac_reward": "100000000",
    "dupe": [
      "foo",
      "bar"
    ]
  }
]
```

```
-ac_supply=1300000 -ac_name=REVS
-ac_supply=816061 -ac_name=SUPERNET
...
-dupe=foo -dupe=bar -ac_supply=1000000000 -ac_name=RFOX -ac_reward=100000000
```

Also fixed a few bugs in the `assetchains` script.

**Comment by lukechilds** [comment]
I intentionally didn't update `src/assetchains.old` as it's out of sync with the `src/assetchains` file, it contains different data and also includes verus which isn't an assetchain in the sense that it can be launched from this `komodod`.

I'm sure there are other files that have assetchain values hardcoded in. Can anyone let me know which they are so I can refactor them to all use the JSON file.

In the future, adding a new assetchain should be as simple as adding a new entry in the JSON, no other file should need to be updated.

**Comment by jl777** [comment]
i dont think there are any other places with assetchain values hardcoded. 
I find assetchains.old very convenient as I can search for a coin and just copy paste that line to launch the chain. if you can generate the equivalent that would be good

**Comment by lukechilds** [comment]
@jl777 You can use just use `./assetchainparams`, it lists all the args:

```shell
$ ./assetchainparams
-ac_supply=1300000 -ac_name=REVS
-ac_supply=816061 -ac_name=SUPERNET
-ac_supply=999999 -ac_name=DEX
-ac_supply=999999 -ac_name=PANGEA
-ac_supply=999999 -ac_name=JUMBLR
-ac_supply=999999 -ac_name=BET
-ac_supply=999999 -ac_name=CRYPTO
-ac_supply=9999999 -ac_name=HODL
-ac_supply=1400000 -ac_name=MSHARK
-ac_supply=999999 -ac_name=BOTS
-ac_supply=999999 -ac_name=MGW
-ac_supply=72000000 -ac_name=COQUI
-ac_supply=210000000 -ac_name=WLC
-ac_supply=1000000 -ac_name=KV
-ac_supply=366666666 -ac_name=CEAL
-ac_supply=1000007 -ac_name=MESH
-ac_supply=257142858 -ac_name=MNZ
-ac_supply=200000000 -ac_name=AXO
-ac_supply=100000000 -ac_name=ETOMIC
-ac_supply=20998641 -ac_name=BTCH
-ac_supply=100000000 -ac_name=PIZZA
-ac_supply=100000000 -ac_name=BEER
-ac_supply=100000000 -ac_name=NINJA
-ac_supply=216000000 -ac_name=OOT
-ac_supply=500000000 -ac_name=BNTN
-ac_supply=999999 -ac_name=CHAIN
-ac_supply=500000000 -ac_name=PRLPAY
-ac_supply=7000000 -ac_name=DSEC
-ac_supply=10000000000 -ac_name=GLXT
-ac_supply=500000000 -ac_name=EQL
-ac_supply=11000000 -ac_name=ZILLA
-ac_supply=1000000000 -ac_name=RFOX -ac_reward=100000000
```

**Comment by lukechilds** [comment]
>i dont think there are any other places with assetchain values hardcoded.

It looks like `src/assetchains_stop` does, but it doesn't look like it's been updated in a while.

https://github.com/jl777/komodo/blob/dev/src/assetchains_stop

**Comment by lukechilds** [comment]
And `src/fiat-cli`

https://github.com/jl777/komodo/blob/dev/src/fiat-cli

**Comment by lukechilds** [comment]
Ok, I've renamed `src/assetchainparams` to `src/listassetchainparams` and also added a new script that just lists the assetchain names `src/listassetchains`. Both generated from the JSON obviously.

Example:

```
$ ./listassetchains
REVS
SUPERNET
DEX
PANGEA
JUMBLR
BET
CRYPTO
HODL
MSHARK
BOTS
MGW
COQUI
WLC
KV
CEAL
MESH
MNZ
AXO
ETOMIC
BTCH
PIZZA
BEER
NINJA
OOT
BNTN
CHAIN
PRLPAY
DSEC
GLXT
EQL
ZILLA
RFOX
```

Also updated `src/assetchains_stop` and `src/fiat-cli` to use `src/listassetchains` and JSON under the hood. Btw there tons of bugs in these two scripts, `src/assetchains_stop` was so broken it literally never could have worked and `src/fiat-cli` would silently ignore any more than 4 arguments. I've fixed all the bugs, but the intended behaviour is still the same.

Also, what's the point of all the `/src/fiat/foo` files? They all need to be called from relative dirs so to actually call it you need to do:

```shell
cd ~/komodo/src && ./fiat/foo getinfo
```

Just calling `komodod` directly is shorter, easier to remember, less error prone and doesn't require whoever added the latest assetchain to have created an arbitrary file and set the correct permissions:

```shell
komodod -ac_name=foo getinfo
```

I think we should delete these. Although this PR has zero breaking changes so far so maybe that should be done at a later date after more warning.

**Comment by lukechilds** [comment]
Just to give an overview, this PR means adding a new assetchain to `src/assetchains.json` will now mean that the following files will automatically work with the new assetchain:

- `src/assetchains`
- `src/assetchains_stop`
- `src/fiat-cli`

And there are two new scripts:

`src/listassetchainparams`: List `komodod` arguments for all assetchains.
`src/listassetchains`: List all assetchain names.

**Comment by lukechilds** [comment]
@jl777 @emmnx @patchkez @blackjok3rtt  I haven't tested this on my node yet, I'm pretty busy this weekend, but will test on Monday and then hopefully can get this merged if everyone's happy with it.

**Comment by lukechilds** [comment]
@jl777 This should be good to merge now

**Pull request merged**
